# -*- coding: utf-8 -*-
"""Composite Generator 30/07/23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N5GmB0mf_HryPVuzXFXHRI81FzDwUvqJ
"""

import numpy as np
import matplotlib.pyplot as plt

#genertor 1
n = 50
m1 = 9
z1 = [5]


for i in range(1,n+1):
    z1[i] = ((3 * (z[i-1])**2) + 5) % m1
    z1.append(new_z1)

#genertor 2
m2 = 15
z2 = [7,11]

for i in range(2,n+1):
    z2[i] = (5*z2[i-1] + 3*z2[i-1] + 16) % m2
    z2.append(new_z2)

#Final generator
final_z = []
u = []
m = 17

for i in range(1,n+1):
     new_z = (z1[i] + z2[i]) % m
     final_z = append(new_z)
     new_u = final_z[i-1] / m
     u.append(new_u)

print(fianl_z)
print(u)

import numpy as np
import matplotlib.pyplot as plt

#genertor 1
n = 50
m1 = 9
z1 = [5]

for i in range(1,n+1):
    new_z1 = ((3 * (z1[i-1])**2) + 5) % m1
    z1.append(new_z1)

#genertor 2
m2 = 15
z2 = [7,11]

for i in range(2,n+1):
    new_z2 = (5*z2[i-1] + 3*z2[i-1] + 16) % m2
    z2.append(new_z2)

#Final generator
final_z = []
u = []
m = 17

for i in range(1,n+1):
     new_z = (z1[i] + z2[i]) % m
     final_z.append(new_z)
     new_u = final_z[i-1] / m
     u.append(new_u)

print(final_z)
print(u)
plt.bar(final_z,u,color = "green")
plt.xlabel("iteration")
plt.ylabel("u value")
plt.show()