# -*- coding: utf-8 -*-
"""General Congruences  30/07/23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15jVJ_6rQA05pU5IyI5dbyhx3bQ7I9HOp
"""

import numpy as np
import matplotlib.pyplot as plt

n = 50
z = [9,5]
u = []
x =[]

for i in range(1,n+1):
    new_z = (2*z[i-1]**2 + 5*z[i-2]+6) % 20
    z.append(new_z)
    new_u = new_z / 20
    u.append(new_u)
    x.append(i)

print(z)
print(u)

plt.bar(x,u,color = "green")
plt.xlabel("iteration")
plt.ylabel("u value")
plt.show()