# -*- coding: utf-8 -*-
"""Inventory_06/08/23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IMS3pnNIB0K2324jLkultNBt2umakedi
"""

import numpy as np
import matplotlib.pyplot as plt

M = 11 #maximum_inventory_capacity
N = 5 #review_period

beginning_inventory = 3
daily_demand = 0
ending_inventory = 0
shortage_quantity = 0
order_quantity = 8
days_until_order_arrives = 3

demand_items = [0,1,2,3,4]
demand_prob = [0.10,0.25,0.35,0.21,0.09]

lead_time = [1,2,3]
lead_time_prob = [0.6,0.3,0.1]

for cycle in range(1,6):
    print("Cycle: ",cycle)

    for day in range(1,N+1):
        print("Day: ",day)

        # check if we have received any order. Check days untile ored arrived
        # reduced days untile ored arrived
        # update begining inventory with order quantity


        daily_demand = np.random.choice(a=[0,1,2,3,4],p=[0.10,0.25,0.35,0.21,0.09])
        # ending_inventory = beginning_inventory - daily_demand
        total_demand = daily_demand + shortage_quantity

        if total_demand > beginning_inventory:

            #shortage
            shortage_quantity = total_demand - beginning_inventory
            ending_inventory = 0
        else:
            ending_inventory = beginning_inventory - total_demand
            shortage_quantity = 0

        print("Beginning_inventory: ",beginning_inventory)
        print("Daily Demand: ",daily_demand)
        print("total_demand: ",total_demand)
        print("Ending_inventory: ",ending_inventory)
        print("Shortage: ",shortage_quantity)

        beginning_inventory = ending_inventory


       # ending_inventory = beginning_inventory - daily_demand

       # check if we have to order item
       # generte random lead_time
       # generate order quantity

    print("\n\n\n")