# -*- coding: utf-8 -*-
"""Monte Carlo 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DLpZj8Tsj97ml_BpoclnvBA8r47c1q2h
"""

import numpy as np
import matplotlib.pyplot as plt



trials=10000
hits=0

a=2
b=3

x1=[]
x2=[]
y1=[]
y2=[]
sum1=0
sum2=0



for i in range(trials):
  x1=np.random.uniform(low=0, high=1)
  #y=(x*np.exp(-x))
  y1=x1
  sum1=sum1+y1
  sum2=sum2 + y1**2

for i in range(trials):
  x2=np.random.uniform(low=1, high=2)
  y2=2-x2
  #y=(x*np.exp(-x))
  sum3=sum1+y2
  sum4=sum2 + y2**2


avg=(sum1+sum3)/trials

avg2=(sum2+sum4)/trials

area=(b-a)*avg

error=((b-a)/np.sqrt(trials))*(np.sqrt(avg2)-np.sqrt(avg)**2)

print(area,error)


plt.bar(x1,y1, color='green',width=.5)
plt.bar(x2,y2, color='red',width=.5)

#plt.bar(area,error, color='green',width=.5)


#plt.scatter(x1,y1, c='green')
#plt.scatter(x2,y2, c='red')