# -*- coding: utf-8 -*-
"""Random No.(1) 30/07/23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eKRRFi7TYoVAqeyBkgn7E6D7q_0NRdXa
"""

import numpy as np
import matplotlib.pyplot as plt

n = 50
z = [7]
u = []
x =[]

for i in range(1,n+1):
    new_z = (5*z[i-1] + 3)  % 16
    z.append(new_z)
    new_u = new_z / 16
    u.append(new_u)
    x.append(i)

print(z)
print(u)

plt.bar(x,u,color = "green")
plt.xlabel("iteration")
plt.ylabel("u value")
plt.show()